### ISSUE TITLE
In Maximage "Customized Example", caption link, video breaks in relative positioning

### ISSUE THREAD

**Issue by arjunmenon** [akv2/MaxImage#31]
hi
if u do this

``` css
#maximage {
    display:none;
    position:relative !important; /* instead of the default "absolute" */
}
```

the caption links behaves like any other text when u hover over it? non-clickable. even the video is now a simple plain cover image.
